# Generated by Django 4.1.2 on 2022-11-01 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneyChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='receiver_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_Name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='sender_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_Name', to=settings.AUTH_USER_MODEL),
        ),
    ]
